### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by rootux** [qtumproject/solar#2]
I've used https://github.com/qtumproject/qtum-bitcore docker image
Installed `Go`, Installed `Solar`.
Run the QTUM daemon on `testnet`
Then when tried to run The following I got:
```
root@0d2a010bcda4:/data/.qtum/luna-to/token/stars-token/node_modules# solar deploy zeppelin-solidity/contracts/token/CappedToken.sol \
>   '[21000000]'
exec: solc [zeppelin-solidity/contracts/token/CappedToken.sol --combined bin,metadata --optimize --allow-paths /data/.qtum/luna-to/token/stars-token/node_modules]
compile: parse solc output: unexpected end of JSON input
```

Same happened when I tried compiling the contract
Would be nice to have a --debug or --verbose flag so we can see the actual parse solc output - this might pure some light on the issue.

**Comment by hayeah** [comment]
my guess is that your environment (or docker container) lacks the `solc` executable.

i've added error reporting for compiler execution error: 

https://github.com/qtumproject/solar/commit/83e590a7ec69b5d245c85e5f6eb5779d1258ea79

One other thing you could try is to manually execute:

```
solc zeppelin-solidity/contracts/token/CappedToken.sol --combined bin,metadata --optimize --allow-paths /data/.qtum/luna-to/token/stars-token/node_modules
```

let me know if this helps

**Comment by hayeah** [comment]
i'll close this issue for now. please reopen if still a problem.
