### ISSUE TITLE
solar command not found - Please add Deploy document

### ISSUE THREAD

**Issue by denuoweb** [qtumproject/solar#21]
mobileapi@html:~/solar-0.0.14/cli/solar$ go get -u github.com/qtumproject/solar/cli/solar

go: finding github.com/qtumproject/solar/cli/solar latest
go: finding golang.org/x/sync latest
go: finding github.com/alecthomas/units latest
go: finding gopkg.in/tomb.v1 latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/net latest
go: finding golang.org/x/crypto latest
go: finding github.com/alecthomas/template latest
go: finding github.com/aristanetworks/goarista latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/jbenet/go-base58 latest
go build golang.org/x/crypto: no Go files in

mobileapi@html:~/solar-0.0.14/cli/solar$ solar
No command 'solar' found, did you mean:
 Command 'solaar' from package 'solaar' (universe)
solar: command not found

**Comment by denuoweb** [comment]
export PATH=$PATH:/home/user/go/bin:$GOPATH/bin
mobile@coin:~/go$ cd bin
bash: cd: bin: No such file or directory

**Comment by hayeah** [comment]
@denuoweb can you `echo $GOPATH` from command line, and see if it's configured?
